server:
  port: 8081

jdbc:
  url: jdbc:mysql://localhost:3306/project-management?serverTimezone=UTC
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver

hibernate:
  dialect: org.hibernate.dialect.MySQL8Dialect
  hbm2ddl.auto: create
  show_sql: true
  format_sql: false
#  naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#  use-new-id-generator-mappings: false
